### PR TITLE
fix(keymap): Save keymap user configuration after changed

### LINKED ISSUE #308: Keymap modifications aren't preserved after page refresh
1. Change a key action
2. Refresh the page

The previously set key action resets, however it should be restored from the local storage.
Introduced by #298

### PR DESCRIPTION
**Pull request by ert78gb**
fix #308 issue

### CODE REVIEW

File: shared/src/store/effects/user-config.ts [hunk 1]
```diff
@@ -26,7 +36,20 @@ export class UserConfigEffects {
             return Observable.of(new LoadUserConfigSuccessAction(config));
         });
 
+    @Effect() saveUserConfig$: Observable<Action> = this.actions$
+        .ofType(KeymapActions.ADD, KeymapActions.DUPLICATE, KeymapActions.EDIT_NAME, KeymapActions.EDIT_ABBR,
+            KeymapActions.SET_DEFAULT, KeymapActions.REMOVE, KeymapActions.SAVE_KEY, KeymapActions.CHECK_MACRO,
+            MacroActions.ADD, MacroActions.DUPLICATE, MacroActions.EDIT_NAME, MacroActions.REMOVE, MacroActions.ADD_ACTION,
+            MacroActions.SAVE_ACTION, MacroActions.DELETE_ACTION, MacroActions.REORDER_ACTION)
+        .withLatestFrom(this.store.select(getUserConfiguration))
+        .switchMap(([action, config]) => {
```
Comment (fjozsef) [inline shared/src/store/effects/user-config.ts]: You could simply map here.

File: shared/src/store/index.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
+import { createSelector } from 'reselect';
```
Comment (fjozsef) [inline shared/src/store/index.ts]: Seems to be unused.
