### PR TITLE
Clear key actions without mutating the original layers

### LINKED ISSUE #339: Agent throws errors when removing all macros
If I delete every macro, I get the following error:

error1

Then if I hit ctrl+o to transfer the whole configuration to the UHK, I get the following error:

error2

This one is quite critical and a blocker because Eric, our firmware development cannot proceed due to this bug, so please fix it ASAP.

### PR DESCRIPTION
**Pull request by fjozsef**
Fixes #339

### CODE REVIEW

File: shared/src/store/reducers/user-configuration.ts [hunk 1]
```diff
@@ -310,22 +310,45 @@ function generateMacroId(macros: Macro[]) {
...
-
-        newLayer.modules = layer.modules.map((module: Module) => {
-            module.keyActions.forEach((action: KeyAction, index: number) => {
+function checkExistence(layers: Layer[], property: string, value: any): Layer[] {
+    const keyActionsToClear: {
+        layer: number,
+        module: number,
+        keyAction: number
+    }[] = [];
+    for (let i = 0; i < layers.length; ++i) {
```
Comment (mondalaci) [inline shared/src/store/reducers/user-configuration.ts]: Please rename `i`, `j`, and `k` to `layerId`, `moduleId`, and `keyActionId` respectively.

Comment (fjozsef) [inline shared/src/store/reducers/user-configuration.ts]: Those are indices, not ids.

Comment (mondalaci) [inline shared/src/store/reducers/user-configuration.ts]: Then possibly `layerIdx`, `moduleIdx`, and `keyActionIdx` would be better names. Normally, I support simple cycle variable names but in this case there are 3 of them and I really feel strongly that this would improve readability.

**Comment by mondalaci** [comment]
@fjozsef Thanks so much for fixing this so quickly!
